import {
  expect,
  type Page,
  type Response as PlaywrightResponse,
  type Locator,
} from "@playwright/test";

export async function byTestId(page: Page, testId: string): Promise<Locator> {
  const locator = page.getByTestId(testId);
  await expect(locator).toBeVisible({ timeout: 30_000 });
  return locator;
}

export async function clickByTestId(page: Page, testId: string) {
  const locator = await byTestId(page, testId);
  await locator.click();
}

export async function fillByTestId(page: Page, testId: string, value: string) {
  const locator = await byTestId(page, testId);
  await locator.fill(value);
}

export async function clickIfPresent(
  page: Page,
  testId: string,
  timeout = 1000,
): Promise<boolean> {
  const locator = page.getByTestId(testId);
  const visible = await locator.isVisible({ timeout }).catch(() => false);
  if (!visible) return false;
  await locator.scrollIntoViewIfNeeded();
  await locator.click();
  return true;
}

export async function waitForAnyVisibleTestId(
  page: Page,
  testIds: readonly string[],
  timeout = 60_000,
  signal?: AbortSignal,
): Promise<string> {
  const deadline = Date.now() + timeout;
  while (Date.now() < deadline) {
    for (const testId of testIds) {
      if (signal?.aborted) throw new Error("Assessment stage wait canceled");
      if (await isVisibleByTestIdOrSemantic(page, testId, 500)) {
        return testId;
      }
      if (signal?.aborted) throw new Error("Assessment stage wait canceled");
    }
  }

  throw new Error(
    `None of these test IDs became visible: ${testIds.join(", ")}`,
  );
}

export async function waitForAssessmentStage(
  page: Page,
  testIds: readonly string[],
  timeout = 360_000,
  signal?: AbortSignal,
): Promise<string> {
  return waitForAnyVisibleTestId(page, testIds, timeout, signal);
}

export async function waitForRetryOutcome(
  page: Page,
  errorTestId: string,
  nextTestIds: readonly string[],
  timeout = 30_000,
): Promise<string> {
  try {
    return await waitForAnyVisibleTestId(page, nextTestIds, timeout);
  } catch (error) {
    if (await isVisibleByTestIdOrSemantic(page, errorTestId, 1000)) {
      return errorTestId;
    }
    throw error;
  }
}

export function semanticLocatorForTestId(
  page: Page,
  testId: string,
): Locator | null {
  switch (testId) {
    case "adaptive-loading-state":
      return page.getByTestId("adaptive-loading");
    case "adaptive-loading-error-state":
      return page
        .getByText(
          /Could not prepare follow-up questions|Follow-up questions are taking too long/i,
        )
        .first();
    case "adaptive-loading-timeout":
      return page
        .getByText(/^Follow-up questions are taking too long$/i)
        .first();
    case "adaptive-loading-retry":
      return page
        .getByRole("button", { name: /retry preparing follow-up questions/i })
        .first();
    case "adaptive-screen":
    case "adaptive-list":
      return page.getByText(/^Adaptive\s*·\s*Q\d+\s+of\s+\d+$/i).first();
    case "review-screen":
      return page.getByTestId("review-ready-title");
    case "assessment-processing":
      return page
        .getByText(
          /Your assessment is being generated by our clinical AI engine|Determining clinical pathway/i,
        )
        .first();
    case "results-screen":
      return page.getByText("Assessment Results").first();
    case "tab-home":
      return page.getByRole("tab", { name: /Home/i }).last();
    case "adaptive-submit":
      return page
        .getByRole("button", {
          name: /^(Continue to next question|Submit answers)$/i,
        })
        .first();
    default:
      return null;
  }
}

export async function isVisibleByTestIdOrSemantic(
  page: Page,
  testId: string,
  timeout = 500,
): Promise<boolean> {
  if (
    await page
      .getByTestId(testId)
      .isVisible({ timeout })
      .catch(() => false)
  )
    return true;
  const semantic = semanticLocatorForTestId(page, testId);
  return (
    semantic != null &&
    (await semantic.isVisible({ timeout }).catch(() => false))
  );
}

export async function actionableLocatorForTestId(
  page: Page,
  testId: string,
): Promise<Locator> {
  const semantic = semanticLocatorForTestId(page, testId);
  if (
    semantic != null &&
    (await semantic.isVisible({ timeout: 500 }).catch(() => false))
  ) {
    return semantic;
  }

  const visibleLocator = page
    .locator(`[data-testid="${testId}"]:visible`)
    .first();
  if (await visibleLocator.isVisible({ timeout: 500 }).catch(() => false))
    return visibleLocator;

  return page.getByTestId(testId).first();
}

export async function visibleDynamicQuestionTestId(
  page: Page,
  questionPrefix: string,
): Promise<string | null> {
  return page
    .locator(`[data-testid^="${questionPrefix}-"]:visible`)
    .evaluateAll((elements, prefix) => {
      const escapedPrefix = prefix.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      const exactQuestionTestId = new RegExp(
        `^${escapedPrefix}-[A-Za-z0-9_]+$`,
      );
      for (const element of elements) {
        const testId = element.getAttribute("data-testid");
        if (testId != null && exactQuestionTestId.test(testId)) {
          return testId;
        }
      }
      return null;
    }, questionPrefix)
    .catch(() => null);
}

export async function waitForDynamicQuestionAdvance(
  page: Page,
  currentScreenTestId: string,
  questionPrefix: string,
  previousQuestionTestId: string | null,
  submitTestId: string,
  nextStageTestIds: readonly string[],
  timeout = 120_000,
): Promise<string> {
  const deadline = Date.now() + timeout;
  while (Date.now() < deadline) {
    for (const testId of nextStageTestIds) {
      if (await isVisibleByTestIdOrSemantic(page, testId, 250)) {
        return testId;
      }
    }

    // Route transitions can briefly unmount the current questionnaire before
    // the authoritative next-stage screen mounts. Keep waiting for an exact
    // next-stage surface instead of treating that transient gap as a result.
    if (!(await isVisibleByTestIdOrSemantic(page, currentScreenTestId, 250))) {
      continue;
    }

    const currentQuestionTestId = await visibleDynamicQuestionTestId(
      page,
      questionPrefix,
    );
    if (
      previousQuestionTestId != null &&
      currentQuestionTestId != null &&
      currentQuestionTestId !== previousQuestionTestId
    ) {
      return currentScreenTestId;
    }

    const submit = await actionableLocatorForTestId(page, submitTestId);
    if (await submit.isVisible({ timeout: 250 }).catch(() => false)) {
      if (
        previousQuestionTestId == null &&
        !(await submit.isEnabled({ timeout: 250 }).catch(() => false))
      ) {
        return currentScreenTestId;
      }
    }
  }

  throw new Error(`Timed out waiting for ${currentScreenTestId} to advance`);
}

export async function maybeContinueSectionTransition(page: Page) {
  await clickIfPresent(page, "screening-section-transition-continue");
}

export async function waitForEnabledAndClick(
  page: Page,
  testId: string,
  timeout = 30_000,
  attempts = 1,
) {
  if (attempts !== 1) {
    throw new Error(
      `Unobserved click retries are not allowed for ${testId}; classify the response before recovering`,
    );
  }
  const locator = await actionableLocatorForTestId(page, testId);
  await expect(locator).toBeVisible({ timeout });
  await expect(locator).toBeEnabled({ timeout });
  await locator.scrollIntoViewIfNeeded();
  await locator.click({ timeout: 10_000 });
}

export async function clickAndWaitForResponse({
  page,
  testId,
  matches,
  timeout = 60_000,
}: {
  page: Page;
  testId: string;
  matches: (response: PlaywrightResponse) => boolean;
  timeout?: number;
}): Promise<PlaywrightResponse> {
  const responsePromise = page.waitForResponse(matches, { timeout });
  await waitForEnabledAndClick(page, testId);
  return responsePromise;
}

export async function isOfflineBannerVisible(page: Page): Promise<boolean> {
  return page
    .getByText(/No internet connection/i)
    .isVisible({ timeout: 1000 })
    .catch(() => false);
}

export async function waitForBrowserNetworkReady(page: Page, timeout = 30_000) {
  await expect
    .poll(
      () =>
        page.evaluate(async () => {
          if (!navigator.onLine) return false;
          try {
            const response = await fetch("/api/health", { cache: "no-store" });
            return response.ok;
          } catch {
            return false;
          }
        }),
      {
        message: "browser context should be online and able to reach the BFF",
        timeout,
      },
    )
    .toBe(true);
}
